apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtual-node.name" . }}
  labels:
      {{- include "virtual-node.labels" . | nindent 4 }}
data:
{{- range $i, $e := until (int .Values.nodeNum) }}
  config-{{ $i }}.json: |-
    {
      "{{ include "virtual-node.name" $ }}-{{ $i }}": {
        "cpu": "64",
        "memory": "256Gi",
        "pods": "600"
      }
    }
{{- end}}
