{{- range $i, $e := until (int .Values.nodeNum) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtual-node.name" $ }}-{{ $i }}
  labels:
    {{- include "virtual-node.labels" $ | nindent 4 }}
    component: {{ include "virtual-node.name" $ }}-{{ $i }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "virtual-node.selectorLabels" $ | nindent 6 }}
      component: {{ include "virtual-node.name" $ }}-{{ $i }}
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "virtual-node.selectorLabels" $ | nindent 8 }}
        component: {{ include "virtual-node.name" $ }}-{{ $i }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "virtual-node.serviceAccountName" $ }}
      volumes:
        - name: config
          configMap:
            name: {{ include "virtual-node.name" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          command:
            - virtual-kubelet
          args:
            - --provider=mock
            - --provider-config=/etc/configmap/config-{{ $i }}.json
            - --nodename={{ include "virtual-node.name" $ }}-{{ $i }}
            {{- if $.Values.disableTaint }}
            - --disable-taint
            {{- end }}
          volumeMounts:
            - mountPath: /etc/configmap
              name: config
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end}}
