{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "virtual-node.serviceAccountName" . }}
  labels:
    {{- include "virtual-node.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "virtual-node.fullname" . }}
  labels:
  {{- include "virtual-node.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "virtual-node.fullname" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "virtual-node.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "virtual-node.fullname" . }}
  labels:
  {{- include "virtual-node.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
